spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/for_video
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
      default_schema: spring3